#!/usr/bin/env python3
"""gen_test_header.py — embed the tests/tls credentials in a C header.

Writes tests/unit/tls_test_data.h: PEM strings (NUL-terminated, as
mbedtls_*_parse wants them), DER certificates, and an RSA-PSS signature made
by OpenSSL for the verification test.  TEST ONLY.

    python3 tests/tls/gen_test_header.py      (needs the openssl CLI)
"""
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "unit", "tls_test_data.h")
PSS_MSG = b"smallest_tcp RSA-PSS test message"


def der(pem):
    return subprocess.run(["openssl", "x509", "-in", os.path.join(HERE, pem),
                           "-outform", "DER"], check=True,
                          capture_output=True).stdout


def c_bytes(name, data):
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 12]) + ",")
    lines.append("};")
    return "\n".join(lines)


def c_pem(name, path):
    text = open(os.path.join(HERE, path)).read()
    body = "".join(f'    "{line}\\n"\n' for line in text.splitlines())
    return f"static const char {name}[] =\n{body};"


def main():
    sig = subprocess.run(
        ["openssl", "dgst", "-sha256", "-sign", os.path.join(HERE, "rsa.key"),
         "-sigopt", "rsa_padding_mode:pss", "-sigopt", "rsa_pss_saltlen:32"],
        input=PSS_MSG, check=True, capture_output=True).stdout
    parts = [
        "/* Generated by tests/tls/gen_test_header.py — TEST ONLY credentials. */",
        "#ifndef TLS_TEST_DATA_H", "#define TLS_TEST_DATA_H", "",
        "#include <stdint.h>", "",
        c_pem("ca_pem", "ca.pem"), "",
        c_pem("server_pem", "server.pem"), "",
        c_pem("server_key_pem", "server.key"), "",
        c_pem("rsa_pem", "rsa.pem"), "",
        c_pem("rsa_key_pem", "rsa.key"), "",
        c_bytes("ca_der", der("ca.pem")), "",
        c_bytes("server_der", der("server.pem")), "",
        c_bytes("rsa_der", der("rsa.pem")), "",
        c_bytes("rsa_pss_msg", PSS_MSG), "",
        c_bytes("rsa_pss_sig", sig), "",
        "#endif", "",
    ]
    open(OUT, "w").write("\n".join(parts))
    print("wrote", os.path.relpath(OUT))


main()
