#!/usr/bin/env python3
"""gen_dtls13.py — C header of DTLS 1.3 key-schedule values.

RFC 9147 §5.9 replaces TLS 1.3's HKDF label prefix "tls13 " by "dtls13".
There is no DTLS 1.3 counterpart of RFC 8448, so this computes the values
with Python's own HMAC-SHA-256 — an implementation independent of the
backend under test — from RFC 8448 §3 secrets (read from
tests/unit/tls_rfc8448.h), with the DTLS prefix.  The same code with the
TLS prefix must reproduce RFC 8448's own values, which it checks first.

Writes tests/unit/tls_dtls13.h.

    python3 tests/tls/gen_dtls13.py
"""
import hashlib
import hmac
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
RFC8448_H = os.path.join(HERE, "..", "unit", "tls_rfc8448.h")
OUT = os.path.join(HERE, "..", "unit", "tls_dtls13.h")


def rfc8448(name):
    text = open(RFC8448_H).read()
    m = re.search(r"static const uint8_t %s\[\d+\] = \{([^}]*)\}" % name, text)
    if not m:
        raise SystemExit("%s not in tls_rfc8448.h" % name)
    return bytes(int(b, 16) for b in re.findall(r"0x([0-9a-f]{2})", m.group(1)))


def hkdf_expand(prk, info, length):
    out, block, i = b"", b"", 1
    while len(out) < length:
        block = hmac.new(prk, block + info + bytes([i]), hashlib.sha256).digest()
        out += block
        i += 1
    return out[:length]


def expand_label(prefix, secret, label, context, length):
    full = prefix + label.encode()
    info = length.to_bytes(2, "big") + bytes([len(full)]) + full
    info += bytes([len(context)]) + context
    return hkdf_expand(secret, info, length)


def derive_secret(prefix, secret, label, transcript_hash):
    return expand_label(prefix, secret, label, transcript_hash, 32)


def main():
    tls, dtls = b"tls13 ", b"dtls13"
    hs_secret = rfc8448("r3_handshake_secret")
    hash_ch_sh = rfc8448("r3_hash_ch_sh")
    s_hs = rfc8448("r3_s_hs_traffic")
    empty = hashlib.sha256(b"").digest()

    # The code must reproduce RFC 8448 with the TLS prefix
    assert derive_secret(tls, hs_secret, "s hs traffic", hash_ch_sh) == s_hs
    assert expand_label(tls, s_hs, "key", b"", 16) == rfc8448("r3_s_hs_key")
    assert expand_label(tls, s_hs, "iv", b"", 12) == rfc8448("r3_s_hs_iv")

    finished_hash = hashlib.sha256(b"dtls13 finished test").digest()
    fk = expand_label(dtls, s_hs, "finished", b"", 32)
    values = [
        ("d13_s_hs_traffic", derive_secret(dtls, hs_secret, "s hs traffic",
                                           hash_ch_sh)),
        ("d13_derived", derive_secret(dtls, hs_secret, "derived", empty)),
        ("d13_key", expand_label(dtls, s_hs, "key", b"", 16)),
        ("d13_iv", expand_label(dtls, s_hs, "iv", b"", 12)),
        ("d13_sn", expand_label(dtls, s_hs, "sn", b"", 16)),
        ("d13_finished_hash", finished_hash),
        ("d13_finished", hmac.new(fk, finished_hash, hashlib.sha256).digest()),
        ("d13_traffic_upd", expand_label(dtls, s_hs, "traffic upd", b"", 32)),
    ]
    lines = [
        "/* Generated by tests/tls/gen_dtls13.py — do not edit.",
        " * DTLS 1.3 (\"dtls13\" label prefix, RFC 9147 §5.9) values from the",
        " * RFC 8448 §3 handshake secret and server handshake traffic secret. */",
        "",
        "#ifndef TLS_DTLS13_H",
        "#define TLS_DTLS13_H",
        "",
        "#include <stdint.h>",
        "",
        "/* clang-format off */",
        "",
    ]
    for name, v in values:
        lines.append("static const uint8_t %s[%d] = {" % (name, len(v)))
        for i in range(0, len(v), 12):
            lines.append("    " + ", ".join("0x%02x" % x for x in v[i:i + 12]) + ",")
        lines.append("};")
        lines.append("")
    lines += ["/* clang-format on */", "", "#endif /* TLS_DTLS13_H */", ""]
    open(OUT, "w").write("\n".join(lines))


if __name__ == "__main__":
    main()
