#!/usr/bin/env python3
"""The stack's external names, for NET_API_PREFIX (include/net_rename.h).

  api_rename.py [--nm NM] --check LIB...   every external symbol the
                                           libraries define is in the header
  api_rename.py [--nm NM] --write LIB...   add those that are not

A project that already has a net_init() of its own, or carries another
stack with a tcp_write(), builds this one with -DNET_API_PREFIX=stcp_ (any
prefix): net_config.h then includes net_rename.h, which renames every
function and object with external linkage — in the stack's sources and in
every file that includes its headers.  The header lists the names; this
script keeps the list whole.  CMake runs --check as the test
api_prefix_covers_every_symbol, in every configuration CI builds, so a new
public function fails it until the header is regenerated:

  cmake --build build && python3 scripts/api_rename.py --write build/libsmallest_tcp_*.a

--write only adds: names another platform or configuration defines stay.
"""

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(ROOT, "include", "net_rename.h")
LINE = re.compile(r"^#define (\w+) NET_API\(\1\)$", re.M)

TOP = """/**
 * @file net_rename.h
 * @brief The stack's external names under a prefix (NET_API_PREFIX).
 *
 * Included by net_config.h when NET_API_PREFIX is defined — to stcp_, say:
 * every function and object of the stack with external linkage is then
 * compiled, and called, under that prefix (net_init() is stcp_net_init()
 * to the linker), so that the stack links beside code that has such names
 * of its own.  The stack's sources and every file that includes its
 * headers must be compiled with the same NET_API_PREFIX.  In those files
 * the plain names still work: they are macros for the prefixed ones.
 * Types, macros and static inline functions are not renamed: they collide
 * only in a file that includes both sets of headers.
 *
 * Generated by scripts/api_rename.py, which also checks it (the test
 * api_prefix_covers_every_symbol): do not edit the list by hand.
 * docs/design/configuration.md §7.
 */

#ifndef NET_RENAME_H
#define NET_RENAME_H

#define NET_API_CAT_(prefix, name) prefix##name
#define NET_API_CAT(prefix, name) NET_API_CAT_(prefix, name)
#define NET_API(name) NET_API_CAT(NET_API_PREFIX, name)

"""
BOTTOM = "\n#endif /* NET_RENAME_H */\n"


def listed():
    if not os.path.exists(HEADER):
        return set()
    with open(HEADER, encoding="utf-8") as f:
        return set(LINE.findall(f.read()))


def defined(nm, libs):
    """External symbols the libraries define, as C names."""
    names = set()
    for lib in libs:
        out = subprocess.run([nm, "-g", "--defined-only", lib], check=True,
                             capture_output=True, text=True).stdout
        for line in out.splitlines():
            parts = line.split()
            if len(parts) != 3:
                continue
            name = parts[2]
            if sys.platform == "darwin" and name.startswith("_"):
                name = name[1:]  # Mach-O's leading underscore
            names.add(name)
    return names


def main(argv):
    nm = "nm"
    if argv[:1] == ["--nm"]:
        nm, argv = argv[1], argv[2:]
    if len(argv) < 2 or argv[0] not in ("--check", "--write"):
        sys.exit(__doc__)
    have, found = listed(), defined(nm, argv[1:])
    prefix = os.environ.get("NET_API_PREFIX", "")
    if prefix:  # libraries built with the prefix: every symbol carries it
        bare = [n for n in sorted(found) if not n.startswith(prefix)]
        if bare:
            sys.exit("not renamed by NET_API_PREFIX (is net_config.h "
                     "included before their declaration?):\n  " +
                     "\n  ".join(bare))
        found = {n[len(prefix):] for n in found}
    missing = sorted(found - have)
    if argv[0] == "--check":
        if missing:
            sys.exit("include/net_rename.h lacks (run scripts/api_rename.py "
                     "--write):\n  " + "\n  ".join(missing))
        return
    with open(HEADER, "w", encoding="utf-8") as f:
        f.write(TOP)
        for name in sorted(have | found):
            f.write("#define %s NET_API(%s)\n" % (name, name))
        f.write(BOTTOM)
    print("%d names, %d new" % (len(have | found), len(missing)))


if __name__ == "__main__":
    main(sys.argv[1:])
